__author__ = 'anderson.amaral@usp.br'

'''ellipsometry.
.'''

import cmath
import math
from math import sin, cos, tan
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt


#P is the angle of incidence
n = 1.52

'''The first calculation is to calculate refractive index using Fresnell Equations'''

#


def ref_index_material():


	result = []
	for theta in ((np.arange(0.0, 90))):

		part1 = float((math.cos(np.radians(theta)))-(math.sqrt(n**2-math.pow(math.sin(np.radians(theta)),2))))
		part2 = float((math.cos(np.radians((theta)))+(math.sqrt(n**2-math.pow(math.sin(np.radians(theta)),2)))))
		part3 = float((math.sqrt(n**2)-(math.pow(math.sin(np.radians(theta)),2)))-((n**2)*(math.cos(np.radians(theta)))))
		part4 = float((math.sqrt(n**2)-(math.pow(math.sin(np.radians(theta)),2)))+((n**2)*(math.cos(np.radians(theta)))))




		Is_Ip_rate =  float(((part1/part2) / (part3/part4))**2)


		print  (Is_Ip_rate)**(-1), Is_Ip_rate



		(result.append((theta/1.32, (Is_Ip_rate)**(-1), (Is_Ip_rate))))

	return result
result1 = ref_index_material()


x = [item[0] for item in result1]
y = [item[1] for item in result1]




plt.scatter(x,y, color = "red")




plt.title('Ip/Is rate x Angle of Incidence')
plt.grid()
plt.xlabel('Angle of Incidence(degrees)')
plt.annotate(' Brewster Angle', xy=(56, 0.3), xytext=(47, 0.5),
            arrowprops=dict(facecolor='black', shrink=0.05),
            )
#plt.annotate(' Generated by Python ', xy=(85, 0.7), xytext=(67, 0.8),
            #arrowprops=dict(facecolor='black', shrink=0.05),
            #)

plt.ylabel('')
plt.show()

z = [item[2] for item in result1]
plt.title('Is/Ip rate x Angle of Incidence')
plt.xlabel('Angle of Incidence (degrees)')
plt.ylim(0,100)
plt.grid()
plt.plot(x,z, color ="red", linewidth = 4)
plt.show()



print
